import Head from "next/head";
import { useSelector, useDispatch } from "react-redux";
import { ConvertionComponent } from "../components/convertionComponent";
import CurrencyExchangeComponent from "../components/currencyExchangeComponent";
import { updateExchangeRate } from "../redux/slices/exchangeRateSlice";

export default function Home() {
  const reduxDispatch = useDispatch();
  const reduxExchangeRate = useSelector(
    (state) => state.exchangeRateReducer.exchangeRate
  );

  const reduxUpdateExchangeRate = (newExchangeRate) => {
    reduxDispatch(updateExchangeRate(newExchangeRate));
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Currency exchange house</h1>
        <hr />

        <br />

        <ConvertionComponent exchangeRate={reduxExchangeRate} />
        <CurrencyExchangeComponent
          exchangeRate={reduxExchangeRate}
          updateExchangeRate={reduxUpdateExchangeRate}
        />
      </main>
    </div>
  );
}
